Repository COW-dev/ddingdong-be, pull requests merged in 2024-11, with the labels that each got.

#167 [DDING-41] FileMetaData 로직 분리
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImpl.java
  src/test/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImplTest.java
Labels: D-3

#160 [DDING-36] Document FileMetadata 로직 적용 및 페이지네이션 구현
  src/main/java/ddingdong/ddingdongBE/common/constant/PageConstant.java
  src/main/java/ddingdong/ddingdongBE/common/converter/FileInfoConverter.java
  src/main/java/ddingdong/ddingdongBE/common/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/ddingdong/ddingdongBE/common/converter/StringListConverter.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ConvertException.java
  src/main/java/ddingdong/ddingdongBE/common/vo/FileInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/api/DocumentApi.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentController.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/CreateDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/GetDocumentPagingRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/UpdateDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DocumentListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/entity/Document.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/repository/DocumentRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/DocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/DocumentServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeAdminDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeAdminDocumentServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeDocumentServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/command/CreateDocumentCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/command/GetDocumentListCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/command/UpdateDocumentCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/query/DocumentListPagingQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/query/DocumentListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/query/DocumentQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/DomainType.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/repository/FileMetaDataRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/UploadedFileUrlAndNameQuery.java
  src/main/resources/db/migration/V23__alter_table_document_drop_column.sql
  src/test/java/ddingdong/ddingdongBE/common/support/WebApiUnitTestSupport.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/service/DocumentServiceImplTest.java
Labels: D-0

#168 [DDING-039] 공지사항 도메인 파일 정책 변경사항 대응
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/DomainType.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/CreateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/UpdateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/entity/Notice.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/CreateNoticeCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/UpdateNoticeCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/query/NoticeQuery.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/UploadedFileUrlAndNameQuery.java
  src/main/resources/data.sql
  src/main/resources/db/migration/V25__alter_table_file_meta_data_key_column.sql
Labels: 🎯리팩토링, D-0

#170 [DDING-40] ActivityReport FileMetaData관련 로직 수정
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/UpdateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeAdminActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeAdminActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/CreateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/UpdateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/DomainType.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/resources/db/migration/V26__alter_table_activityreport_drop_column.sql
Labels: D-1

#174 [DDING-000] FileMetaDataService null 체킹 로직 추가
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/resources/db/migration/V23__alter_table_document_drop_column.sql
  src/main/resources/db/migration/V26__alter_table_activityreport_drop_column.sql
Labels: 🎯리팩토링

#175 [DDING-000] ImageId Null값 허용 로직 추가
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
Labels: 🎯리팩토링, D-0

#176 [DDING-000] Club, FixZone 테스트 에러 수정
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImplTest.java
Labels: 🛠️버그

#179 [DDING-000] 공지사항 생성 및 수정 API의 필드명 일부 변경
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/CreateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/UpdateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/CreateNoticeCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/UpdateNoticeCommand.java
Labels: 🎯리팩토링, D-0

#178 [DDING-000] 페이지네이션 오류 수정 및 FileMetaData 로직 수정
  src/main/java/ddingdong/ddingdongBE/domain/documents/repository/DocumentRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/test/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImplTest.java
Labels: D-3

#180 [DDING-000] mysql 컨테이너 볼륨 설정
  compose-dev.yaml
Labels: 🛠️버그

#181 [DDING-000] 테이블 복구를 위한 볼륨 연결 스크립트 추가
  compose-dev.yaml
Labels: 🚨긴급, 🛠️버그, D-0
