Repository COW-dev/ddingdong-be, pull requests merged in 2024-09, with the labels that each got.

#96 [DEV-000] 동아리원 명단 다운로드 파일 메뉴얼 이미지 추가
  src/main/java/ddingdong/ddingdongBE/file/service/ExcelFileService.java
  src/main/resources/static/club_member_excel_menual.png
Labels: 🎯리팩토링, D-0

#98 [DEV-000] @ModelAttribute를 사용하던 Request DTO에서 @RequestPart로 롤백
  .github/workflows/dev-server-integrator.yml
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/UpdateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
  src/main/java/ddingdong/ddingdongBE/file/service/ExcelFileService.java
  src/test/java/ddingdong/ddingdongBE/file/service/ExcelFileServiceTest.java
Labels: 🚨긴급, 🛠️버그, D-0

#100 [DEV-000] 활동보고서 현재 회차 정보 변경 및 자료실 불필요 필드 제거
  .github/workflows/dev-server-integrator.yml
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/GenerateDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/ModifyDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/AdminDetailDocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DetailDocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/entity/Document.java
  src/main/resources/db/migration/V3__document_delete_content_column.sql
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/service/DocumentServiceTest.java
Labels: D-0

#102 [DEV-56] 활동 보고서 활동 일자 update 케이스 정리 및 로직 작성
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/AdminActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
Labels: 🚨긴급, 🛠️버그, D-1

#101 [DEV-50] 동아리별 피드 전체 조회 API
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/api/FeedApi.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/FeedController.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/FeedListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/Feed.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/FeedType.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FeedService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/data.sql
  src/main/resources/db/migration/V4__Create_feed.sql
  src/test/java/ddingdong/ddingdongBE/common/support/FixtureMonkeyFactory.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java
Labels: D-3

#103 [release] v1.0.1
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/AdminActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
Labels: 🛠️버그, D-0, ⭐️배포

#106 [DEV-000] CI(test) 오류 수정
  src/main/resources/application-local.yml
  src/main/resources/data.sql
  src/main/resources/db/migration/V4__Create_feed.sql
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeClubMemberServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java
Labels: 💯테스트, 🎯리팩토링, D-0

#107 [DEV-000] Feed 엔티티 컬럼 타입 수정
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/Feed.java
  src/main/resources/db/migration/V4__Create_feed.sql
Labels: 🚨긴급, 🎯리팩토링, D-0

#108 [DEV-000] Feed 엔티티 컬럼 제약 조건 제거
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/Feed.java
  src/main/resources/db/migration/V4__Create_feed.sql
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeClubMemberServiceTest.java
Labels: 💯테스트, 🚨긴급, D-0

#109 [DEV-000] feedRepositoryTest 에러 수정
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java
Labels: 🚨긴급, 🛠️버그, D-3

#112 [DEV-57] local 환경 flyway, db 환경 설정 변경
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReportTermInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/entity/Banner.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/ClubMember.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/entity/Document.java
  src/main/java/ddingdong/ddingdongBE/domain/fileinformation/entity/FileInformation.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/entity/FixZone.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/entity/FixZoneComment.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/entity/Notice.java
  src/main/java/ddingdong/ddingdongBE/domain/question/entity/Question.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/entity/ScoreHistory.java
  src/main/java/ddingdong/ddingdongBE/domain/user/entity/User.java
  src/main/resources/application-local.yml
  src/main/resources/db/migration/V8__apply_key_name_convention.sql
Labels: 🎯리팩토링, ⚒️설정, D-0

#114 [DEV-000] 동아리 피드 상세조회 API 응답값에 동아리 ID 추가
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/FeedResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/ClubInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/ClubProfileQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/FeedQuery.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java
Labels: 🎯리팩토링, D-1

#116 [DEV-000] Hotfix - 프로필 이미지 에러 수정
  src/main/java/ddingdong/ddingdongBE/domain/feed/api/FeedApi.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/Feed.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
  src/main/resources/application-local.yml
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java
Labels: 🚨긴급, 🛠️버그

#118 [DEV-000] 픽스존 댓글 content 필드 타입을 text로 변경하는 스크립트 작성
  src/main/resources/db/migration/V9__alter_fix_zone_comment_content_type.sql
Labels: D-0

#119 [DEV-000] 동아리 연락처 형식 검증을 위한 정규 표현식 변경
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/PhoneNumber.java
Labels: 🎯리팩토링, D-0

#120 [DEV-004] 모니터링을 위한 Grafana, Prometheus, Spring Actuator 설정
  build.gradle
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 📖문서, 🌍인프라, D-1

#122 [release] v1.1.1
  build.gradle
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/PhoneNumber.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: D-0

#123 [DEV-000] VO에 @EqualsAndHashCode 적용
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/PhoneNumber.java
  src/main/resources/application-prod.yml
Labels: 🎯리팩토링, D-2

#124 [release] v1.1.2
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/PhoneNumber.java
  src/main/resources/application-prod.yml
Labels: D-1

#121 [DEV-74] ActivityReport 리팩토링
  src/main/java/ddingdong/ddingdongBE/common/utils/TimeParser.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/AdminActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityTermInfoRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/UpdateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportDto.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportTermInfoResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/CurrentTermResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReportTermInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/repository/ActivityReportRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/repository/ActivityReportTermInfoRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/CreateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/CreateActivityTermInfoCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/UpdateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportTermInfoQuery.java
Labels: 🎯리팩토링, D-1

#126 [DEV-000] ActivityReport Facade 서비스 분리
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeAdminActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
Labels: D-3

#127 [DEV-5]로그 수집을 위한 promtail 설정
  .ebextensions/01-set-timezone.config
  .ebextensions/02-install-docker-compose.config
  .github/workflows/prod-server-deployer.yml
  promtail-config.yml
  promtail-docker-compose.yml
  promtail/promtail-config.yml
  promtail/promtail-docker-compose.yml
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomExceptionHandler.java
  src/main/java/ddingdong/ddingdongBE/common/runner/PromtailDockerComposeRunner.java
  src/main/resources/application-prod.yml
  src/main/resources/logback-prod.xml
Labels: 📖문서, 🌍인프라, ⚒️설정, D-0

#128 [DEV-000] Event 관련 파일 삭제
  src/main/java/ddingdong/ddingdongBE/domain/event/controller/EventController.java
  src/main/java/ddingdong/ddingdongBE/domain/event/controller/dto/request/ApplyEventRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/event/controller/dto/response/EventQrResponse.java
Labels: 🎯리팩토링
