Repository COW-dev/ddingdong-be, pull requests merged in 2024-10, with the labels that each got.

#132 [DEV-000] ActivityReport 응답 필드명 수정
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportQuery.java
Labels: 🛠️버그

#131 [DEV-000] EventQr 관련 잔여 클래스 파일 삭제
  src/main/java/ddingdong/ddingdongBE/common/utils/EventQrGenerator.java
Labels: 🎯리팩토링, D-3

#133 [DEV-000] 활동보고서 삭제 API 에러 수정
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
Labels: 🛠️버그, D-1

#134 [DEV-000] Document도메인 Controller -> Service 데이터 이동 방법 수정
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentController.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentController.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/CreateDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/UpdateDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeAdminDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/command/CreateDocumentCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/command/UpdateDocumentCommand.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerUnitTest.java
Labels: 🎯리팩토링, D-1

#136 [DEV-40] FileMetaData 기능 구현
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/AdminDocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeAdminDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/query/AdminDocumentQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/query/DocumentQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/fileinformation/service/FileInformationService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileCategory.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/repository/FileMetaDataRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/GeneralFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/DetailNoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeService.java
  src/main/java/ddingdong/ddingdongBE/file/AwsS3FileStore.java
  src/main/java/ddingdong/ddingdongBE/file/FileStore.java
  src/main/java/ddingdong/ddingdongBE/file/controller/dto/response/UploadUrlResponse.java
  src/main/java/ddingdong/ddingdongBE/file/service/ExcelFileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/FileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/ExcelClubMemberDto.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/FileResponse.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/UploadFileDto.java
  src/main/resources/db/migration/V10__create_file_meta_data_table.sql
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/file/service/S3FileServiceTest.java
Labels: ✨기능, D-0

#130 [DEV-76] Notice 도메인 리팩토링
  src/main/java/ddingdong/ddingdongBE/domain/fileinformation/service/FileInformationService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/api/AdminNoticeApi.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/api/NoticeApi.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/AdminNoticeApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/AdminNoticeController.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/NoticeApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/NoticeController.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/CreateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/RegisterNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/UpdateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/DetailNoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/entity/Notice.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/repository/NoticeRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeNoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/CreateNoticeCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/UpdateNoticeCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/query/NoticeListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/query/NoticeQuery.java
Labels: 🎯리팩토링, D-0

#139 [DDING-000] CI 실패 부분 수정
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeNoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/query/NoticeQuery.java
Labels: 🛠️버그

#142 [DDING-014] AI 코드리뷰를 위한 coderabbit 도입
  .coderabbit.yaml
Labels: 🌍인프라

#138 [DDING-3] ScoreHistory 도메인 리팩토링 적용
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/AdminScoreHistoryApi.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/ClubScoreHistoryApi.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/AdminScoreHistoryController.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/ClubScoreHistoryController.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/request/CreateScoreHistoryRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/ScoreHistoryListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeAdminScoreHistoryService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeAdminScoreHistoryServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeClubScoreHistoryService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeClubScoreHistoryServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/GeneralScoreHistoryService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/ScoreHistoryService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/command/CreateScoreHistoryCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/AdminClubScoreHistoryListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/ClubScoreHistoryListQuery.java
  src/main/resources/logback-prod.xml
  src/test/java/ddingdong/ddingdongBE/common/support/WebApiUnitTestSupport.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/controller/AdminScoreHistoryControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/controller/ClubScoreHistoryControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeAdminScoreHistoryServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeClubScoreHistoryServiceImplTest.java
Labels: 🎯리팩토링, D-0

#140 [DDING-000] ClubMember 도메인 패키지 분리
  src/main/generated/ddingdong/ddingdongBE/domain/club/entity/QClub.java
  src/main/generated/ddingdong/ddingdongBE/domain/club/entity/QClubMember.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/UpdateClubMemberRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/ClubMemberResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/club/repository/ClubMemberRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/entity/ClubMember.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/repository/ClubMemberRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/ClubMemberService.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeClubMemberService.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeClubMemberServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/GeneralClubMemberService.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/dto/command/UpdateClubMemberCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/dto/command/UpdateClubMemberListCommand.java
  src/main/java/ddingdong/ddingdongBE/file/service/ExcelFileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/ExcelClubMemberDto.java
  src/test/java/ddingdong/ddingdongBE/common/support/WebApiUnitTestSupport.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeGeneralClubMemberServiceTest.java
  src/test/java/ddingdong/ddingdongBE/file/service/ExcelFileServiceTest.java
Labels: 🎯리팩토링, D-0

#144 [DDING-000] 컴파일 오류 수정
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/AdminScoreHistoryApi.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/ClubScoreHistoryApi.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/AdminScoreHistoryController.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/ClubScoreHistoryController.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/AdminScoreHistoryListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/ClubScoreHistoryListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/AdminClubScoreHistoryListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/ClubScoreHistoryListQuery.java
  src/test/java/ddingdong/ddingdongBE/common/support/WebApiUnitTestSupport.java
Labels: 🎯리팩토링, D-0

#146 [DDING-4] Club 도메인 리팩토링
  .gitignore
  src/main/generated/ddingdong/ddingdongBE/domain/club/entity/QClub.java
  src/main/generated/ddingdong/ddingdongBE/domain/user/entity/QUser.java
  src/main/java/ddingdong/ddingdongBE/auth/controller/dto/request/SignInRequest.java
  src/main/java/ddingdong/ddingdongBE/auth/service/JwtAuthService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/api/AdminClubApi.java
  src/main/java/ddingdong/ddingdongBE/domain/club/api/CentralClubApi.java
  src/main/java/ddingdong/ddingdongBE/domain/club/api/UserClubApi.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/AdminClubApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/AdminClubController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/UserClubApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/UserClubController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/CreateClubRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/UpdateClubInfoRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/UpdateClubRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AdminClubListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AdminClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/ClubMemberResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/ClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/DetailClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/MyClubInfoResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/UserClubListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/UserClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeAdminClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeAdminClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/GeneralClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/command/CreateClubCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/command/UpdateClubInfoCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/query/AdminClubListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/query/MyClubInfoQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/query/UserClubListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/query/UserClubQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeClubMemberServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/AdminFixZoneController.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeAdminScoreHistoryServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/GeneralScoreHistoryService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/ScoreHistoryService.java
  src/main/java/ddingdong/ddingdongBE/domain/user/entity/User.java
  src/main/java/ddingdong/ddingdongBE/domain/user/repository/UserRepository.java
  src/main/resources/db/migration/V11__drop_column_club_content.sql
  src/main/resources/db/migration/V12__alter_user_userid_name.sql
  src/test/java/ddingdong/ddingdongBE/common/support/WithMockAuthenticatedUser.java
  src/test/java/ddingdong/ddingdongBE/common/support/WithMockAuthenticatedUserSecurityContextFactory.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeAdminClubServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeClubMemberServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeAdminScoreHistoryServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeClubScoreHistoryServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/user/repository/UserRepositoryTest.java
Labels: 🎯리팩토링, D-0

#145 [DDING-000] FileMetaData DTO 생성
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/FileMetaDataCommand.java
Labels: D-1

#143 [DDING-15] presignedUrl contentType 지정 로직 추가
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/GeneralFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/CreateFileMetaDataCommand.java
  src/main/java/ddingdong/ddingdongBE/file/AwsS3FileStore.java
  src/main/java/ddingdong/ddingdongBE/file/api/S3FileAPi.java
  src/main/java/ddingdong/ddingdongBE/file/controller/S3FileController.java
  src/main/java/ddingdong/ddingdongBE/file/controller/dto/response/UploadUrlResponse.java
  src/main/java/ddingdong/ddingdongBE/file/service/ContentType.java
  src/main/java/ddingdong/ddingdongBE/file/service/FileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/command/GeneratePreSignedUrlRequestCommand.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/GeneratePreSignedUrlRequestQuery.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/UploadedFileUrlQuery.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/UploadedVideoUrlQuery.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V13__alter_file_meta_data_table_column.sql
  src/test/java/ddingdong/ddingdongBE/file/service/S3FileServiceTest.java
Labels: 🎯리팩토링, D-0

#147 [DDING-6] Banner 이미지 presingedUrl 적용
  .DS_Store
  .gitignore
  promtail/.DS_Store
  src/main/generated/ddingdong/ddingdongBE/common/QBaseEntity.java
  src/main/generated/ddingdong/ddingdongBE/domain/activityreport/domain/QActivityReport.java
  src/main/generated/ddingdong/ddingdongBE/domain/activityreport/domain/QActivityReportTermInfo.java
  src/main/generated/ddingdong/ddingdongBE/domain/activityreport/domain/QParticipant.java
  src/main/generated/ddingdong/ddingdongBE/domain/banner/entity/QBanner.java
  src/main/generated/ddingdong/ddingdongBE/domain/club/entity/QClub.java
  src/main/generated/ddingdong/ddingdongBE/domain/club/entity/QLocation.java
  src/main/generated/ddingdong/ddingdongBE/domain/club/entity/QPhoneNumber.java
  src/main/generated/ddingdong/ddingdongBE/domain/documents/entity/QDocument.java
  src/main/generated/ddingdong/ddingdongBE/domain/feed/entity/QFeed.java
  src/main/generated/ddingdong/ddingdongBE/domain/fileinformation/entity/QFileInformation.java
  src/main/generated/ddingdong/ddingdongBE/domain/fixzone/entity/QFixZone.java
  src/main/generated/ddingdong/ddingdongBE/domain/fixzone/entity/QFixZoneComment.java
  src/main/generated/ddingdong/ddingdongBE/domain/notice/entity/QNotice.java
  src/main/generated/ddingdong/ddingdongBE/domain/question/entity/QQuestion.java
  src/main/generated/ddingdong/ddingdongBE/domain/scorehistory/entity/QScore.java
  src/main/generated/ddingdong/ddingdongBE/domain/scorehistory/entity/QScoreHistory.java
  src/main/generated/ddingdong/ddingdongBE/domain/user/entity/QUser.java
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomExceptionHandler.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/api/AdminBannerApi.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/api/UserBannerApi.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/controller/AdminBannerController.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/controller/UserBannerController.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/controller/dto/request/CreateBannerRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/controller/dto/request/UpdateBannerRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/controller/dto/response/AdminBannerListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/controller/dto/response/BannerResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/controller/dto/response/UserBannerListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/entity/Banner.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/repository/BannerRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/BannerService.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/FacadeAdminBannerService.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/FacadeAdminBannerServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/FacadeUserBannerService.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/FacadeUserBannerServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/GeneralBannerService.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/dto/command/CreateBannerCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/dto/query/AdminBannerListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/dto/query/UserBannerListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileCategory.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/GeneralFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/CreateFileMetaDataCommand.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V14__alter_table_banner.sql
  src/test/java/ddingdong/ddingdongBE/common/support/TestContainerSupport.java
  src/test/java/ddingdong/ddingdongBE/domain/banner/service/FacadeAdminBannerServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/banner/service/FacadeUserBannerServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeClubMemberServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/question/service/FacadeAdminQuestionServiceImplTest.java
Labels: 🎯리팩토링, D-0

#148 [DDING-000] 테스트 오류 수정
  src/test/java/ddingdong/ddingdongBE/domain/banner/service/FacadeAdminBannerServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/banner/service/FacadeUserBannerServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/question/service/FacadeUserQuestionServiceImplTest.java
Labels: 💯테스트, D-0

#149 [DDING-5] Club 도메인 presingedUrl 적용
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/FacadeAdminBannerServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/api/CentralClubApi.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/UserClubController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/UpdateClubInfoRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AdminClubListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/MyClubInfoResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/UserClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeAdminClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/GeneralClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/command/UpdateClubInfoCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/query/AdminClubListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/query/MyClubInfoQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/query/UserClubQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/GeneralFileMetaDataService.java
  src/main/resources/db/migration/V15__alter_table_club_add_column.sql
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeAdminClubServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImplTest.java
Labels: 🎯리팩토링, D-1

#150 [DDING-7] Document Presigned URL 적용
  src/main/java/ddingdong/ddingdongBE/common/converter/StringListConverter.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ConvertException.java
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomExceptionHandler.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/api/AdminDocumentApi.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentController.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/CreateDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/UpdateDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/AdminDocumentListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/AdminDocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/entity/Document.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/DocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeAdminDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/command/CreateDocumentCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/command/UpdateDocumentCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/query/AdminDocumentListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/query/AdminDocumentQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/dto/query/DocumentQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileCategory.java
  src/main/resources/db/migration/V16__alter_table_document_add_column.sql
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentControllerUnitTest.java
Labels: D-3

#151 [DDING-8] ActivityReport Presigned URL 적용
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequests.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/UpdateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/UpdateActivityReportRequests.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/CreateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/UpdateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileCategory.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/GeneralFileMetaDataService.java
  src/main/resources/db/migration/V17__alter_table_activity_report_add_column.sql
Labels: D-3

#154 [DDING-000] 동아리 api uri 수정
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/club/api/CentralClubApi.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/ClubScoreHistoryApi.java
Labels: 📖문서, 🎯리팩토링, D-0

#156 [DDING-000] urlQuery null 체킹 추가
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/controller/dto/response/AdminBannerListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/controller/dto/response/UserBannerListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/MyClubInfoResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/UserClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DocumentResponse.java
Labels: 🎯리팩토링, D-0

#157 [DDOING-000] 동아리원 명단 조회 API 분리
  src/main/java/ddingdong/ddingdongBE/domain/club/api/CentralClubApi.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/CentralClubMemberListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/MyClubInfoResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeCentralClubMemberService.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeCentralClubMemberServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/dto/query/CentralClubMemberListQuery.java
  src/test/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeCentralClubMemberServiceTest.java
Labels: 🎯리팩토링

#155 [DDING-32] FixZone 도메인 리팩토링 및 presignedUrl 적용
  src/main/java/ddingdong/ddingdongBE/common/converter/StringListConverter.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/AdminFixZoneController.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/ClubFixZoneController.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/api/AdminFixZoneApi.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/api/ClubFixZoneApi.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/CreateFixZoneCommentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/CreateFixZoneRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFixZoneCommentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFixZoneRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFixZoneStatusRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/AdminFixZoneListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/AdminFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/CentralFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/CentralMyFixZoneListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/GetDetailFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/GetFixZoneCommentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/entity/FixZone.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/entity/FixZoneComment.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminFixZoneCommentService.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminFixZoneCommentServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminFixZoneService.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminFixZoneServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneService.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FixZoneCommentService.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FixZoneCommentServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FixZoneService.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FixZoneServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/command/CreateFixZoneCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/command/CreateFixZoneCommentCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/command/UpdateFixZoneCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/command/UpdateFixZoneCommentCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/query/AdminFixZoneListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/query/AdminFixZoneQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/query/CentralFixZoneQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/query/CentralMyFixZoneListQuery.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/main/resources/db/migration/V19__alter_table_fix_zone_add_image_key_column.sql
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminFixZoneCommentServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminFixZoneServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImplTest.java
Labels: 🎯리팩토링, D-1

#152 [DDING-011] 공지사항 API Presigned Url 적용 및 Offset 기반 페이지네이션 적용
  src/main/java/ddingdong/ddingdongBE/common/converter/FileInfoConverter.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ConvertException.java
  src/main/java/ddingdong/ddingdongBE/common/vo/FileInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/AdminClubController.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileCategory.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/api/AdminNoticeApi.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/api/NoticeApi.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/AdminNoticeController.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/NoticeController.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/CreateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/GetNoticePagingRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/UpdateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/entity/Notice.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/repository/NoticeRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeNoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/CreateNoticeCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/GetNoticeListCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/UpdateNoticeCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/query/NoticeListPagingQuery.java
  src/main/resources/db/migration/V20__alter_table_notice_add_file_column.sql
Labels: ✨기능, D-0

#159 [DDING-035] 공지사항 상세 조회 API 응답 명세 변경
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/repository/NoticeRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/query/NoticeQuery.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/UploadedFileUrlQuery.java
Labels: D-3

#162 [DDING-37] FileMetaData 도메인 변경
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/service/FacadeAdminBannerServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/UpdateClubInfoRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AdminClubListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/MyClubInfoResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/UserClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeAdminClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/command/UpdateClubInfoCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/query/MyClubInfoQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeAdminDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/DomainType.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileStatus.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/repository/FileMetaDataRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/GeneralFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/command/CreateFileMetaDataCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/command/UpdateAllFileMetaDataCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/query/FileMetaDataListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminFixZoneServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/file/controller/dto/response/UploadUrlResponse.java
  src/main/java/ddingdong/ddingdongBE/file/service/ContentType.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/GeneratePreSignedUrlRequestQuery.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/UploadedFileUrlQuery.java
  src/main/resources/db/migration/V21__alter_table_file_meta_data.sql
  src/main/resources/db/migration/V22__alter_table_club_drop_column.sql
  src/main/resources/db/migration/V23__alter_table_file_meta_data_key_column.sql
  src/test/java/ddingdong/ddingdongBE/domain/banner/service/FacadeAdminBannerServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeAdminClubServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/file/service/S3FileServiceTest.java
Labels: 🎯리팩토링, D-0

#161 [DDING-000] 공지사항 페이지 수 반환 로직 버그 수정
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeServiceImpl.java
Labels: D-0

#164 [DDING-38] FixZone 파일 로직 수정
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeAdminClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/FacadeAdminDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/DomainType.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FacadeFileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/command/CreateFileMetaDataCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/command/UpdateAllFileMetaDataCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/query/FileMetaDataListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/CreateFixZoneRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFixZoneRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/AdminFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/CentralFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/entity/FixZone.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminFixZoneServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/command/CreateFixZoneCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/command/UpdateFixZoneCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/test/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImplTest.java
Labels: 🎯리팩토링, D-0

#165 [DDING-000] 테스트 오류 제거
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
Labels: 💯테스트, 🎯리팩토링, D-0

#166 [DDING-000] api 오류 수정
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AdminClubListResponse.java
Labels: 🛠️버그, D-0
