Repository COW-dev/ddingdong-be, pull requests merged in 2024-08, with the labels that each got.

#65 [DEV-000] jacoco 의존성 제거
  build.gradle
Labels: 🌍인프라

#67 [DEV-000] MySQL Dialect 및 ddl-auto 옵션 변경
  src/main/resources/application-dev.yml
Labels: 🌍인프라, ⚒️설정

#68 [DEV-000] 개발 서버 구축 및 에러 핸들링
  src/main/resources/application-dev.yml
Labels: 🌍인프라, 🛠️버그

#69 [DEV-22] 이미지 요청 최대 파일 크기 10MB에서 20MB로 확장
  .github/workflows/ddingdong-dev-deploy.yml
  README.md
  build.gradle
  src/main/java/ddingdong/ddingdongBE/common/config/OpenApiConfig.java
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ErrorMessage.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ExceptionController.java
  src/main/java/ddingdong/ddingdongBE/common/utils/EventQrGenerator.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/ClubMemberDto.java
  src/main/java/ddingdong/ddingdongBE/domain/club/repository/ClubMemberRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubMemberService.java
  src/main/java/ddingdong/ddingdongBE/domain/event/controller/EventController.java
  src/main/java/ddingdong/ddingdongBE/domain/event/controller/dto/request/ApplyEventRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/event/controller/dto/response/EventQrResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fileinformation/entity/FileDomainCategory.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/AdminEventController.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/UserEventController.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/request/CollectStampRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/response/AppliedUsersResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/response/CollectedStampsResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/response/CollectionResultResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/controller/dto/response/DetailAppliedUserResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/entity/ClubStamp.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/entity/StampHistory.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/repository/StampHistoryRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/service/QrStampService.java
  src/main/java/ddingdong/ddingdongBE/file/service/FileService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🚨긴급, 🛠️버그

#70 [DEV-000] 픽스존 상세 조회에서 동아리 위치와 이름 조회 가능하도록 변경
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/api/ClubFixZoneApi.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/GetDetailFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FixZoneService.java
Labels: 🛠️버그, 🎯리팩토링

#71 [DEV-000] CD 배포 스크립트 수정
  .github/workflows/dev-server-deployer.yml
Labels: 🌍인프라, 🛠️버그

#72 [DEV-000] 활동보고서 수정 api 오류
  src/main/java/ddingdong/ddingdongBE/common/handler/RestAuthenticationEntryPoint.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
Labels: 🛠️버그, 🎯리팩토링

#73 [DEV-34] 서버 타임존 변경
  .github/codeowners
  src/main/java/ddingdong/ddingdongBE/DdingdongBeApplication.java
Labels: 🎯리팩토링, D-0

#74 [DEV-35] dn-rule 적용
  .github/workflows/dn-rule.yml
Labels: ⚒️설정, D-0

#77 [DEV-000]Dialect 오류 수정
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
Labels: 🛠️버그

#81 [DEV-000] ci 도커 에러 수정
  .github/workflows/dev-server-integrator.yml
  Dockerfile
  build.gradle
  src/main/resources/application-test.yml
  src/test/java/ddingdong/ddingdongBE/common/support/TestContainerSupport.java
Labels: D-2

#76 [DEV-26] soft-delete 설정 및 flyway 적용
  build.gradle
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReport.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReportTermInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/banner/entity/Banner.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/ClubMember.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/entity/Document.java
  src/main/java/ddingdong/ddingdongBE/domain/fileinformation/entity/FileInformation.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/entity/FixZone.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/entity/FixZoneComment.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/entity/Notice.java
  src/main/java/ddingdong/ddingdongBE/domain/qrstamp/entity/StampHistory.java
  src/main/java/ddingdong/ddingdongBE/domain/question/entity/Question.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/entity/ScoreHistory.java
  src/main/java/ddingdong/ddingdongBE/domain/user/entity/User.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__Add_softdelete_column.sql
  src/test/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReportTest.java
Labels: ✨기능, ⚒️설정, D-0

#82 [DEV-29] 에러 핸들러 및 커스텀 에러 정의
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomException.java
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomExceptionHandler.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ErrorResponse.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ExceptionController.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ExceptionResponse.java
  src/main/java/ddingdong/ddingdongBE/common/exception/PersistenceException.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
Labels: D-0

#79 [DEV-28] 동아리 점수내역 swagger + validation 명세
  src/main/java/ddingdong/ddingdongBE/auth/service/JwtAuthService.java
  src/main/java/ddingdong/ddingdongBE/common/exception/AuthenticationException.java
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomException.java
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomExceptionHandler.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ErrorMessage.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ErrorResponse.java
  src/main/java/ddingdong/ddingdongBE/common/exception/InvalidatedMappingException.java
  src/main/java/ddingdong/ddingdongBE/common/exception/PersistenceException.java
  src/main/java/ddingdong/ddingdongBE/common/handler/RestAuthenticationEntryPoint.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/AdminClubApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/UserClubApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/RegisterClubRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/AdminScoreHistoryApi.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/ClubScoreHistoryApi.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/AdminScoreHistoryController.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/ClubScoreHistoryController.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/request/CreateScoreHistoryRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/request/RegisterScoreRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/entity/Score.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/entity/ScoreCategory.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/ScoreHistoryService.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/controller/AdminScoreHistoryControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/controller/ClubScoreHistoryControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/entity/ScoreCategoryTest.java
Labels: 📖문서, 🎯리팩토링, D-0

#84 [DEV-000] README 적용
  README.md
Labels: D-2

#83 [DEV-000] 에러 핸들러 명세 일부 수정
  src/main/java/ddingdong/ddingdongBE/auth/service/JwtAuthService.java
  src/main/java/ddingdong/ddingdongBE/common/exception/AuthenticationException.java
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomExceptionHandler.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ErrorMessage.java
  src/main/java/ddingdong/ddingdongBE/common/exception/RegisterClubException.java
Labels: 🎯리팩토링, D-1

#86 [DEV-39] presignedUrl 발급 API
  build.gradle
  src/main/java/ddingdong/ddingdongBE/common/exception/AwsException.java
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomException.java
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomExceptionHandler.java
  src/main/java/ddingdong/ddingdongBE/domain/club/api/CentralClubApi.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/RegisterClubRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Location.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/PhoneNumber.java
  src/main/java/ddingdong/ddingdongBE/file/api/S3FileAPi.java
  src/main/java/ddingdong/ddingdongBE/file/controller/S3FileController.java
  src/main/java/ddingdong/ddingdongBE/file/controller/dto/response/UploadUrlResponse.java
  src/main/java/ddingdong/ddingdongBE/file/dto/ExcelClubMemberDto.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/test/java/ddingdong/ddingdongBE/domain/club/entity/LocationTest.java
  src/test/java/ddingdong/ddingdongBE/file/service/ExcelFileServiceTest.java
  src/test/java/ddingdong/ddingdongBE/file/service/S3FileServiceTest.java
Labels: D-0

#88 [DEV-41] querydsl 셋업
  build.gradle
  settings.gradle
  src/main/java/ddingdong/ddingdongBE/common/BaseEntity.java
  src/main/java/ddingdong/ddingdongBE/common/config/QueryDslConfig.java
  src/main/java/ddingdong/ddingdongBE/common/exception/PersistenceException.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/AdminScoreHistoryApi.java
Labels: ⚒️설정, D-3

#89 [DEV-46] 공지사항 전체 조회 API offset 기반 페이지네이션 적용
  src/main/java/ddingdong/ddingdongBE/domain/notice/api/NoticeApi.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/NoticeApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/GetAllNoticeByPageRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/DetailNoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/GetAllNoticeByPageResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/repository/NoticeRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeService.java
Labels: ✨기능, D-0

#91 [DEV-47] 자료실 API offset 기반 페이지네이션 적용
  src/main/java/ddingdong/ddingdongBE/domain/documents/api/AdminDocumentApi.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/api/DocumentApi.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentController.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/GetDocumentByPageRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/GetDocumentByPageResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/repository/DocumentRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/DocumentService.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentControllerUnitTest.java
Labels: ✨기능, 💯테스트, D-0

#92 [DEV-000] 활동보고서 시작일자 변경 및 테스트 에러 해결
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
Labels: D-1

#90 [DEV-45] Club 도메인 presignedUrl 로직 적용
  src/main/java/ddingdong/ddingdongBE/common/exception/CustomExceptionHandler.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ErrorMessage.java
  src/main/java/ddingdong/ddingdongBE/domain/club/api/CentralClubApi.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/UserClubApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/UpdateClubRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/ClubListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/ClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/DetailClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/UpdateClubCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentController.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentController.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/AdminDetailDocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DetailDocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fileinformation/service/FileInformationService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/DetailNoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/NoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/entity/Score.java
  src/main/java/ddingdong/ddingdongBE/file/AwsS3FileStore.java
  src/main/java/ddingdong/ddingdongBE/file/FileStore.java
  src/main/java/ddingdong/ddingdongBE/file/api/S3FileApi.java
  src/main/java/ddingdong/ddingdongBE/file/controller/S3FileController.java
  src/main/java/ddingdong/ddingdongBE/file/controller/dto/request/FileMetaDataRequest.java
  src/main/java/ddingdong/ddingdongBE/file/controller/dto/response/FileUrlResponse.java
  src/main/java/ddingdong/ddingdongBE/file/controller/dto/response/UploadUrlResponse.java
  src/main/java/ddingdong/ddingdongBE/file/entity/FileCategory.java
  src/main/java/ddingdong/ddingdongBE/file/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/file/repository/FileMetaDataRepository.java
  src/main/java/ddingdong/ddingdongBE/file/service/ExcelFileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/FacadeFileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/file/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/file/service/FileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/ExcelClubMemberDto.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/FileMetaDataCommand.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/FileResponse.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/FileUrlDto.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/UploadFileDto.java
  src/main/resources/data.sql
  src/main/resources/db/migration/V3__dev-45.sql
  src/test/java/ddingdong/ddingdongBE/common/support/FixtureMonkeyFactory.java
  src/test/java/ddingdong/ddingdongBE/domain/club/entity/LocationTest.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeClubMemberServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentControllerUnitTest.java
  src/test/java/ddingdong/ddingdongBE/file/service/S3FileServiceTest.java
Labels: D-0

#94 [DEV-000]: presignedUrl contentType 지정
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/request/UpdateClubRequest.java
  src/main/java/ddingdong/ddingdongBE/file/api/S3FileApi.java
  src/main/java/ddingdong/ddingdongBE/file/controller/S3FileController.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/main/resources/data.sql
  src/test/java/ddingdong/ddingdongBE/file/service/S3FileServiceTest.java
Labels: 🎯리팩토링, D-0

#95 [DEV-000] presignedUrl 발급 API 응답 예시 설정
  src/main/java/ddingdong/ddingdongBE/file/api/S3FileApi.java
Labels: 📖문서
