Repository COW-dev/ddingdong-be, pull requests merged in 2024-07, with the labels that each got.

#57 [DEV-12] Swagger 의존성 추가
  build.gradle
  src/main/java/ddingdong/ddingdongBE/common/config/OpenApiConfig.java
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/logback-spring.xml
  src/main/resources/sentry-appender.xml
Labels: ⚒️설정

#58 [DEV-6] 활동 보고서 회차별 기간 API
  build.gradle
  src/main/java/ddingdong/ddingdongBE/auth/PrincipalDetails.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ExceptionController.java
  src/main/java/ddingdong/ddingdongBE/common/handler/RestAuthenticationEntryPoint.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/AdminActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityTermInfoRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportTermInfoResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/domain/ActivityReportTermInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/repository/ActivityReportTermInfoRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoService.java
Labels: ✨기능

#59 [DEV-18] 자료실 API
  build.gradle
  src/main/java/ddingdong/ddingdongBE/common/BaseEntity.java
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ErrorMessage.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/api/AdminDocumentApi.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/api/DocumentApi.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentController.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentController.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/GenerateDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/request/ModifyDocumentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/AdminDetailDocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/AdminDocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DetailDocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/controller/dto/response/DocumentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/entity/Document.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/repository/DocumentRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/DocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/fileinformation/entity/FileDomainCategory.java
  src/main/java/ddingdong/ddingdongBE/file/dto/FileResponse.java
  src/main/java/ddingdong/ddingdongBE/file/dto/UploadFileDto.java
  src/main/resources/application-test.yml
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/AdminDocumentControllerTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/controller/DocumentControllerTest.java
  src/test/java/ddingdong/ddingdongBE/domain/documents/service/DocumentServiceTest.java
  src/test/java/ddingdong/ddingdongBE/support/WebAdaptorTestSupport.java
Labels: ✨기능

#60 [DEV-10] Fix Zone API 리팩토링 및 Fix Zone Comment API 개발
  src/main/java/ddingdong/ddingdongBE/common/converter/MultipartJackson2HttpMessageConverter.java
  src/main/java/ddingdong/ddingdongBE/common/exception/ErrorMessage.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/AdminActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/CurrentTermResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/DetailActivityReportResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/AdminFixZoneController.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/ClubFixZoneController.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/api/AdminFixZoneApi.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/api/ClubFixZoneApi.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/CreateFixZoneCommentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/CreateFixZoneRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFixZoneCommentRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFixZoneRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFixZoneStatusRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/AdminDetailFixResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/AdminFixResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/ClubDetailFixResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/ClubFixResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/GetDetailFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/GetFixZoneCommentResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/GetFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/entity/FixZone.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/entity/FixZoneComment.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/repository/FixZoneCommentRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/repository/FixZoneRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FixZoneCommentService.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FixZoneService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/ScoreHistoryService.java
Labels: ✨기능, 🎯리팩토링

#61 PR[#59] build 오류 수정
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/user/entity/User.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/data.sql
Labels: 🎯리팩토링

#63 [DEV-9] 동아리 평가 점수 조회 로직 수정
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/AdminScoreHistoryApi.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/api/ClubScoreHistoryApi.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/AdminScoreHistoryController.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/ClubScoreHistoryController.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/request/RegisterScoreRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/ScoreHistoryFilterByClubResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/entity/ScoreCategory.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/entity/ScoreHistory.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/ScoreHistoryService.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/controller/AdminScoreHistoryControllerTest.java
  src/test/java/ddingdong/ddingdongBE/domain/scorehistory/controller/ClubScoreHistoryControllerTest.java
  src/test/java/ddingdong/ddingdongBE/support/WebApiTestSupport.java
Labels: 🎯리팩토링
