Repository COW-dev/ddingdong-be, pull requests merged in 2025-01, with the labels that each got.

#195 [DEV-56] Vod Processing Job 생성 API 구현
  build.gradle
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/java/ddingdong/ddingdongBE/domain/documents/service/GeneralDocumentService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/GeneralFixZoneService.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/GeneralNoticeService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/VodProcessingJobController.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/dto/request/CreatePendingVodProcessingJobRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/ConvertJobStatus.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodNotificationStatus.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodProcessingJob.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodProcessingNotification.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/repository/VodProcessingJobRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingJobService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingJobServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/GeneralVodProcessingJobService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/VodProcessingJobService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/dto/command/CreatePendingVodProcessingJobCommand.java
  src/main/java/ddingdong/ddingdongBE/file/controller/S3FileController.java
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/command/GeneratePreSignedUrlRequestCommand.java
  src/main/resources/db/migration/V29__create_tables_vod_processing.sql
  src/test/java/ddingdong/ddingdongBE/domain/documents/service/GeneralDocumentServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminGeneralFixZoneServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralGeneralFixZoneServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeGeneralVodProcessingJobServiceTest.java
  src/test/java/ddingdong/ddingdongBE/file/service/S3FileServiceTest.java
Labels: ✨기능, 🎯리팩토링, D-0

#196 [DDING-64] presignedUrl - 이미지 순서 적용 구현
  build.gradle
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/FileMetaData.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/dto/FileMetaDataIdOrderDto.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/api/ClubFixZoneApi.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/CreateFixZoneRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/request/UpdateFixZoneRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/AdminFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/controller/dto/response/CentralFixZoneResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeAdminFixZoneServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralFixZoneServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/command/CreateFixZoneCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/command/UpdateFixZoneCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/query/AdminFixZoneQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/fixzone/service/dto/query/CentralFixZoneQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/api/AdminNoticeApi.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/api/NoticeApi.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/AdminNoticeController.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/NoticeController.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/CreateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/request/UpdateNoticeRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/controller/dto/response/NoticeResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeAdminNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/FacadeNoticeServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/CreateNoticeCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/command/UpdateNoticeCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/notice/service/dto/query/NoticeQuery.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/UploadedFileUrlAndNameWithOrderQuery.java
  src/main/java/ddingdong/ddingdongBE/file/service/dto/query/UploadedFileUrlWithOrderQuery.java
  src/main/resources/db/migration/V30__alter_table_file_meta_data_add_column_order.sql
  src/test/java/ddingdong/ddingdongBE/domain/fixzone/service/FacadeCentralGeneralFixZoneServiceTest.java
Labels: 🎯리팩토링, D-0

#198 [DDING-000] 람다 트리깅 인증 규칙 수정
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/VodProcessingJobController.java
Labels: 🚨긴급, 🎯리팩토링, D-0

#197 [DDING-53] Feed 생성 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/feed/api/ClubFeedApi.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/ClubFeedController.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/request/CreateFeedRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/Feed.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/FeedType.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/command/CreateFeedCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/FeedListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/FeedQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/DomainType.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/resources/db/migration/V31__feed_url_modify_nullable.sql
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/file/service/S3FileServiceTest.java
Labels: D-3

#199 [DDING-54] Feed 수정 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/feed/api/ClubFeedApi.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/ClubFeedController.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/request/UpdateFeedRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/Feed.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/command/UpdateFeedCommand.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImplTest.java
Labels: ✨기능, D-0

#200 [DDING-55] Feed 삭제 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/feed/api/ClubFeedApi.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/ClubFeedController.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/FeedType.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/DomainType.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImplTest.java
Labels: ✨기능, D-3

#201 [DDING-66] ClubMember 목록 조회 API 응답값 변경
  src/main/java/ddingdong/ddingdongBE/domain/club/api/CentralClubApi.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/CentralClubController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/AllClubMemberInfoResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/dto/response/CentralClubMemberListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeCentralClubMemberService.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeCentralClubMemberServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/dto/query/AllClubMemberInfoQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/dto/query/CentralClubMemberListQuery.java
Labels: D-3

#203 [DDING-47] media convert job status 업데이트 API 구현
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/VodProcessingJobController.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/dto/request/CreatePendingVodProcessingJobRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/dto/request/UpdateVodProcessingJobStatusRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/ConvertJobStatus.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodProcessingJob.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingJobService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingJobServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/dto/command/UpdateVodProcessingJobStatusCommand.java
  src/test/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeGeneralVodProcessingJobServiceTest.java
Labels: ✨기능, D-0

#204 [DDING-000] VodProcessingJob 필드 수정
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/dto/request/CreatePendingVodProcessingJobRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodProcessingJob.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingJobServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/dto/command/CreatePendingVodProcessingJobCommand.java
  src/main/resources/db/migration/V32__alter_table_vod_proceessing_job_add_column.sql
  src/test/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeGeneralVodProcessingJobServiceTest.java
Labels: 🎯리팩토링, D-0

#205 [DDING-51] VodProcessingJob 완료 시 notification 전송 구현
  src/main/java/ddingdong/ddingdongBE/common/exception/SseException.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/entity/Feed.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/dto/request/UpdateVodProcessingJobStatusRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodNotificationStatus.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodProcessingJob.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodProcessingNotification.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/repository/VodProcessingJobRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/repository/VodProcessingNotificationRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingJobServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/GeneralVodProcessingJobService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/GeneralVodProcessingNotificationService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/VodProcessingJobService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/VodProcessingNotificationService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/dto/command/CreatePendingVodProcessingJobCommand.java
  src/main/java/ddingdong/ddingdongBE/sse/repository/SseConnectionMapRepository.java
  src/main/java/ddingdong/ddingdongBE/sse/repository/SseConnectionRepository.java
  src/main/java/ddingdong/ddingdongBE/sse/service/SseConnectionService.java
  src/main/java/ddingdong/ddingdongBE/sse/service/dto/SseEvent.java
  src/test/java/ddingdong/ddingdongBE/common/support/DataJpaTestSupport.java
  src/test/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeCentralClubMemberServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/vodprocessing/repository/VodProcessingJobRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeGeneralVodProcessingJobServiceMockingTest.java
  src/test/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeGeneralVodProcessingJobServiceTest.java
  src/test/java/ddingdong/ddingdongBE/sse/service/SseConnectionServiceTest.java
Labels: ✨기능, 🎯리팩토링, D-0

#206 [DDING-65] Feed 조회 API 구현 및 커서 기반 페이지네이션 적용
  src/main/java/ddingdong/ddingdongBE/domain/feed/api/FeedApi.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/FeedController.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/ClubFeedPageResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/FeedListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/FeedResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/NewestFeedListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/NewestFeedPerClubPageResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/PagingResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/ClubFeedPageQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/ClubProfileQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/FeedFileUrlQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/FeedListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/FeedQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/NewestFeedPerClubPageQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/PagingQuery.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedServiceTest.java
Labels: ✨기능, 🎯리팩토링, D-0

#207 [DDING-000] Feed thumbnail 조회 버그 수정
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
Labels: 🛠️버그

#208 [DDING-50] SSE ACK API 구현
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/api/VodProcessingNotificationApi.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/VodProcessingJobInternalController.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/VodProcessingNotificationController.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/dto/request/AckNotificationRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodProcessingNotification.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingJobServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingNotificationService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingNotificationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/GeneralVodProcessingNotificationService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/VodProcessingNotificationService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/dto/command/UpdateAckedNotificationCommand.java
  src/main/java/ddingdong/ddingdongBE/sse/api/SseConnectionApi.java
  src/main/java/ddingdong/ddingdongBE/sse/service/dto/SseVodProcessingNotificationDto.java
  src/test/java/ddingdong/ddingdongBE/domain/vodprocessing/service/FacadeVodProcessingNotificationServiceImplTest.java
Labels: ✨기능, 🎯리팩토링

#209 [DDING-000] Feed 내 동아리 프로필 조회 nullable하게 수정
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
Labels: D-3

#210 [DDING-000] validation 오류 수정
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/controller/dto/request/CreatePendingVodProcessingJobRequest.java
Labels: 🛠️버그, 🎯리팩토링, D-0

#212 [DDING-000] videoUrl directory path 수정
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
Labels: 🛠️버그, 🎯리팩토링, D-0

#213 [DDING-000] videoUrl directory path 수정(2)
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
Labels: 🛠️버그, 🎯리팩토링, D-0

#215 [DDING-000] Image CDN URL 구성요소 수정
  src/main/java/ddingdong/ddingdongBE/file/service/S3FileService.java
Labels: 🚨긴급, 🎯리팩토링

#216 [DDING-78] 중앙동아리 피드 목록 조회 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/feed/api/ClubFeedApi.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/ClubFeedController.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/request/CreateFeedRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/MyFeedPageResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FeedFileService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/command/CreateFeedCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/MyFeedPageQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodProcessingJob.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/GeneralVodProcessingJobService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/service/VodProcessingJobService.java
  src/main/java/ddingdong/ddingdongBE/file/service/ContentType.java
Labels: ✨기능, D-2

#217 [DDING-79] FileMetaData 테이블 내 사용하지 않은 컬럼 제거
  src/main/resources/db/migration/V33__drop_column_file_meta_data.sql
Labels: D-2

#218 [DDING-000] 테스트 에러 수정
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImplTest.java
Labels: 🛠️버그

#219 [DDING-000] 피드가 존재하지 않을 경우 발생하는 에러 수정
  src/main/java/ddingdong/ddingdongBE/domain/feed/controller/dto/response/MyFeedPageResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/ClubFeedPageQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/MyFeedPageQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/NewestFeedPerClubPageQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/dto/query/PagingQuery.java
Labels: 🛠️버그

#220 [DDING-80] 활동보고서 현재 회차 조회 API 로직 수정 및 페이지네이션 로직 수정
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/repository/ActivityReportTermInfoRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeClubFeedServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/FacadeFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/vodprocessing/entity/VodProcessingJob.java
  src/main/resources/application-prod.yml
  src/test/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedServiceTest.java
  src/test/java/ddingdong/ddingdongBE/domain/question/service/FacadeUserQuestionServiceImplTest.java
Labels: D-0

#224 [DDING-000] urlEncoded 파일명 decode 로직 추가
  src/main/java/ddingdong/ddingdongBE/file/controller/S3FileController.java
Labels: 🎯리팩토링, D-0

#225 [DDING-81] 동영상 Converting 상태 검증 쿼리 작성
  src/main/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
Labels: 🎯리팩토링, D-3

#226 [DDING-82] OSIV 비활성화로 인한 지연로딩 에러 수정
  src/main/java/ddingdong/ddingdongBE/domain/club/repository/ClubRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/GeneralClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeCentralClubMemberServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/AdminScoreHistoryListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/ClubScoreHistoryListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeAdminScoreHistoryServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeClubScoreHistoryServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/AdminClubScoreHistoryListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/ClubScoreHistoryListQuery.java
Labels: 🛠️버그, D-3

#228 [release] v.1.2.1
  .github/codeowners
  src/main/java/ddingdong/ddingdongBE/domain/club/repository/ClubRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/GeneralClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/service/FacadeCentralClubMemberServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/feed/service/GeneralFeedService.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/AdminScoreHistoryListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/controller/dto/response/ClubScoreHistoryListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeAdminScoreHistoryServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/FacadeClubScoreHistoryServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/AdminClubScoreHistoryListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/scorehistory/service/dto/query/ClubScoreHistoryListQuery.java
  src/main/java/ddingdong/ddingdongBE/file/controller/S3FileController.java
  src/test/java/ddingdong/ddingdongBE/domain/feed/repository/FeedRepositoryTest.java
Labels: D-2

#230 [DDING-85] 동아리 지원폼지 생성 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/CreateFormRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/CreateFormCommand.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImplTest.java
Labels: D-2
