Repository COW-dev/ddingdong-be, pull requests merged in 2025-03, with the labels that each got.

#279 [DDING-000] 통계 전체 조회 중 파일 조회 문제 해결
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/SingleFieldStatisticsResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/TextFieldStatisticsResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FormField.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/SingleFieldStatisticsQuery.java
  src/main/resources/db/migration/V41__alter_table_form_field_option.sql
Labels: 🎯리팩토링, D-2

#280 [DDING-000] OSIV 속성 on
  src/main/resources/application-prod.yml
Labels: 🚨긴급, 🛠️버그, D-0

#284 [DDING-121] 활동보고서 현재 회차 조회 로직 수정
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportServiceImpl.java
Labels: 🎯리팩토링, D-0

#285 [release] v1.3.2
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportServiceImpl.java
  src/main/resources/db/migration/V42__alter_table_add_index_activity_report.sql
Labels: ⭐️배포

#286 [DDING-122] 활동보고서 조회 API 수정
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/AdminActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/UpdateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/AdminActivityReportListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/CentralActivityReportListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/entity/ActivityReport.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/entity/ActivityReportTermInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/entity/Participant.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/repository/ActivityReportRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/repository/ActivityReportTermInfoRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeAdminActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeAdminActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/CreateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/UpdateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportTermInfoQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/AdminActivityReportListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/CentralActivityReportListQuery.java
  src/test/java/ddingdong/ddingdongBE/domain/activityreport/entity/ActivityReportTest.java
Labels: 🎯리팩토링, D-1

#290 [release] v1.3.3
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/AdminActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/ClubActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/ClubActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/CreateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/request/UpdateActivityReportRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/ActivityReportResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/AdminActivityReportListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/CentralActivityReportListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/entity/ActivityReport.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/entity/ActivityReportTermInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/entity/Participant.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/repository/ActivityReportRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/repository/ActivityReportTermInfoRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/ActivityReportTermInfoServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeAdminActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeAdminActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeClubActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/CreateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/UpdateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/ActivityReportTermInfoQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/AdminActivityReportListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/CentralActivityReportListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/club/repository/ClubRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/club/repository/dto/UserClubListInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/ClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/GeneralClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/query/UserClubListQuery.java
  src/test/java/ddingdong/ddingdongBE/domain/activityreport/entity/ActivityReportTest.java
  src/test/java/ddingdong/ddingdongBE/domain/club/repository/ClubRepositoryTest.java
Labels: ⭐️배포

#291 [DDING-000] 어드민 - 활동보고서 상세 조회 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/api/AdminActivityReportApi.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/AdminActivityReportApiController.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/controller/dto/response/AdminActivityReportListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeAdminActivityReportService.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/FacadeAdminActivityReportServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/query/AdminActivityReportListQuery.java
Labels: 🎯리팩토링, D-0

#293 [DDING-124] 폼지 종료일자 수정 API 구현
  src/main/java/ddingdong/ddingdongBE/common/exception/FormException.java
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/UpdateFormEndDateRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/UpdateFormEndDateCommand.java
Labels: D-3

#292 [DDING-000] 통계 전체조회시 파일 조회 쿼리 개선 및 응답값 수정
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/SingleFieldStatisticsQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormApplicationRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/dto/FileAnswerInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FileFormAnswerService.java
  src/test/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormApplicationRepositoryTest.java
Labels: 🎯리팩토링, D-0

#294 [DDING-001] 폼지 수정 로직 개선
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/entity/ClubMember.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/UpdateFormRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/FormResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FormField.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/UpdateFormCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/entity/FormAnswer.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/entity/FormApplication.java
  src/main/resources/db/migration/V43__alter_table_form_application_and_form_answer.sql
  src/test/java/ddingdong/ddingdongBE/domain/form/entity/FormTest.java
Labels: 🎯리팩토링, D-0

#295 [DDING-125-1] 섹션 여러 개일 경우 폼지 생성 수정
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FormField.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/CreateFormCommand.java
Labels: 🎯리팩토링, D-0

#297 [DDING - 126] 동아리 목록 조회 및 폼지 조회 로컬 캐싱 적용
  build.gradle
  src/main/java/ddingdong/ddingdongBE/common/config/cache/CacheConfig.java
  src/main/java/ddingdong/ddingdongBE/domain/club/controller/UserClubController.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/GeneralClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/UserFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormService.java
  src/main/java/ddingdong/ddingdongBE/email/SesEmailService.java
  src/main/resources/application-local.yml
Labels: 🎯리팩토링, D-0
