Repository COW-dev/ddingdong-be, pull requests merged in 2025-04, with the labels that each got.

#298 [DDING-000] 폼지 섹션별 생성 조회 롤백
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FormField.java
  src/main/java/ddingdong/ddingdongBE/domain/form/repository/FormFieldRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/CreateFormCommand.java
Labels: D-5

#299 [DDING-000] Form 제거시 Form과 연관된 FileMetaData 삭제로직 구현
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FormAnswerService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/GeneralFormAnswerService.java
  src/test/java/ddingdong/ddingdongBE/common/fixture/FileMetaDataFixture.java
  src/test/java/ddingdong/ddingdongBE/common/fixture/FormFixture.java
  src/test/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepositoryTest.java
Labels: D-0

#300 [DDING-000] 통계 조회시 권한 확인 로직 추가
  src/main/java/ddingdong/ddingdongBE/common/exception/FormException.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
Labels: D-0

#301 [DDING-000] 최근 폼지 구하기 로직 위치 수정
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FormStatus.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Forms.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/FormListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationServiceImpl.java
Labels: 🎯리팩토링, D-0
