Repository COW-dev/ddingdong-be, pull requests merged in 2025-02, with the labels that each got.

#231 [DDING-86] 동아리 지원 폼지 수정 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/club/service/GeneralClubService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/UpdateFormRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FormField.java
  src/main/java/ddingdong/ddingdongBE/domain/form/repository/FormFieldRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/UpdateFormCommand.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImplTest.java
Labels: D-2

#233 [DDING-91] 지원하기 API 구현
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/api/UserFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/controller/UserFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/controller/dto/request/CreateFormApplicationRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/entity/FormAnswer.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/entity/FormApplication.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/entity/FormApplicationStatus.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/repository/FormAnswerRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/repository/FormApplicationRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/FacadeUserFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/FacadeUserFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/FormAnswerService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/FormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/GeneralFormAnswerService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/GeneralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/dto/CreateFormApplicationCommand.java
  src/main/resources/db/migration/V35_create_form_response_and_answer_table.sql
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormServiceImplTest.java
Labels: D-3

#232 [DDING-87] 동아리 지원 폼지 삭제 API 구현
  src/main/java/ddingdong/ddingdongBE/common/exception/AuthenticationException.java
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/controller/UserFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/controller/dto/request/CreateFormApplicationRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/entity/FormAnswer.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/FacadeUserFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/FacadeUserFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplicaion/service/dto/CreateFormApplicationCommand.java
  src/main/resources/db/migration/V35_create_form_response_and_answer_table.sql
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormServiceImplTest.java
Labels: D-2

#237 [DDING-88] 동아리 지원 폼지 전체 조회 API 구현
  src/main/java/ddingdong/ddingdongBE/common/utils/TimeUtils.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/CreateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/activityreport/service/dto/command/UpdateActivityReportCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/FormListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/repository/FormRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/FormListQuery.java
  src/test/java/ddingdong/ddingdongBE/common/utils/TimeUtilsTest.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImplTest.java
Labels: D-0

#240 [DDING-95] 지원자 상세 조회 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/api/CentralFormApplicationApi.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/CentralFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/FormApplicationResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FormAnswerService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/GeneralFormAnswerService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/GeneralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/FormApplicationQuery.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormApplicationServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImplTest.java
Labels: D-2

#241 [DDING-93] 지원자 상태 수정 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/FormQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/api/CentralFormApplicationApi.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/api/UserFormApplicationApi.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/CentralFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/UserFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/request/UpdateFormApplicationStatusRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/entity/FormApplication.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/entity/FormApplicationStatus.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/GeneralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/command/UpdateFormApplicationStatusCommand.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormApplicationServiceImplTest.java
Labels: D-2

#244 [DEV-000] V36 flyway script 수정
  src/main/resources/db/migration/V36__form_add_column_sections.sql
Labels: 🛠️버그, 🎯리팩토링, D-0

#246 [DDING-000] 지원자 전체 조회 API 누락된 정보 추가
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/CreateFormRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/UpdateFormRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/FormListResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/FormResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FieldType.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FormField.java
  src/main/java/ddingdong/ddingdongBE/domain/form/repository/FormFieldRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/form/repository/FormRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormFieldService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/CreateFormCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/UpdateFormCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/FormListQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/FormQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/CentralFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/UserFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/request/CreateFormApplicationRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/request/UpdateFormApplicationStatusRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/FormApplicationResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/MyFormApplicationPageResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/PagingResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/entity/FormAnswer.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/entity/FormApplication.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/entity/FormApplicationStatus.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormApplicationRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FormAnswerService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/GeneralFormAnswerService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/GeneralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/command/CreateFormApplicationCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/command/UpdateFormApplicationStatusCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/FormApplicationQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/MyFormApplicationPageQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/PagingQuery.java
Labels: D-2

#245 [DDING-102] 폼지 섹션 조회 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/form/api/UserFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/UserFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/FormSectionResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/FormSectionQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/UserFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormApplicationServiceImpl.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormApplicationServiceImplTest.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormServiceImplTest.java
Labels: D-3

#242 [DDING-97] 동아리 지원 폼지 통계 전체조회 API 구현
  src/main/java/ddingdong/ddingdongBE/common/utils/CalculationUtils.java
  src/main/java/ddingdong/ddingdongBE/common/utils/TimeUtils.java
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/FormStatisticsResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/repository/FormFieldRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/form/repository/dto/FieldListInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/FormStatisticsQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormApplicationRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/dto/DepartmentInfo.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/dto/RecentFormInfo.java
  src/test/java/ddingdong/ddingdongBE/common/support/FixtureMonkeyFactory.java
  src/test/java/ddingdong/ddingdongBE/common/utils/CalculationUtilsTest.java
  src/test/java/ddingdong/ddingdongBE/domain/form/repository/FormApplicationRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/form/repository/FormFieldRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticServiceImplTest.java
Labels: D-0

#248 [DDING-000] 지원자 조회 API 수정
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/FormApplicationResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/MyFormApplicationPageResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/FormApplicationQuery.java
Labels: D-0

#243 [DDING-103] 폼지 생성 및 수정시 기간 중복 검증 로직 구현
  src/main/java/ddingdong/ddingdongBE/common/exception/InvalidatedMappingException.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/CreateFormRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/UpdateFormRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FieldType.java
  src/main/java/ddingdong/ddingdongBE/domain/form/repository/FormRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/GeneralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/CreateFormCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/UpdateFormCommand.java
  src/test/java/ddingdong/ddingdongBE/domain/form/repository/FormRepositoryTest.java
  src/test/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImplTest.java
Labels: D-1

#247 [DDING-107] 최종 합격 지원자 동아리원 명단 등록 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/club/entity/Club.java
  src/main/java/ddingdong/ddingdongBE/domain/clubmember/entity/ClubMember.java
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/entity/FormApplication.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormApplicationRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/GeneralFormApplicationService.java
  src/main/resources/db/migration/V38__alter_table_form_application_add_column.sql
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeAdminClubServiceImplTest.java
Labels: ✨기능, D-0

#252 [DDING-98] 지원 폼지 통계 객관식 상세조회 API 구현
  src/main/java/ddingdong/ddingdongBE/common/converter/StringListConverter.java
  src/main/java/ddingdong/ddingdongBE/common/exception/InvalidatedMappingException.java
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/MultipleFieldStatisticsResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FormField.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/MultipleFieldStatisticsQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepository.java
  src/test/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepositoryTest.java
Labels: D-3

#254 [DDING-99] 동아리 폼지 통계 주관식 상세조회 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/TextFieldStatisticsResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/FormField.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FormStatisticServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/TextFieldStatisticsQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/dto/TextAnswerInfo.java
  src/test/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormAnswerRepositoryTest.java
Labels: D-3

#258 [DDING-111] 지원자 전체 조회 API 페이지네이션 제거
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/api/CentralFormApplicationApi.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/CentralFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/MyFormApplicationsResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/PagingResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormApplicationRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/GeneralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/MyFormApplicationsQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/PagingQuery.java
Labels: 🎯리팩토링, D-0

#255 [DDING-110] 지원자 상세조회시 파일 다운로드 로직 처리
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/api/CentralFormApplicationApi.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/CentralFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/MyAllFormApplicationsResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/entity/FormAnswer.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/FormApplicationQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/MyAllFormApplicationsQuery.java
Labels: D-3

#257 [DDING-000] 동아리 지원하기 - File Type 답변 로직 추가
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/entity/DomainType.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormApplicationServiceImpl.java
Labels: 🎯리팩토링, D-0

#261 [DDING-001] UserFormResponse에 질문 id 필드 추가
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/UserFormResponse.java
Labels: D-0

#263 [DDING-113] 지원자 수 조회 API 구현
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/api/UserFormApplicationApi.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/UserFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/FormApplicationCountResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/FormApplicationCountQuery.java
Labels: D-3

#267 [DDING-000] 폼지 수정내 기간 검증로직 오류 수정
  src/main/java/ddingdong/ddingdongBE/domain/form/entity/Form.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
Labels: D-3

#268 [DDING-000] 지원하기 요청 dto 필드 추가 및 폼지 상세 조회 응답에 지원자 수 필드 추가
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/UserFormResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/UserFormQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/api/UserFormApplicationApi.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/UserFormApplicationController.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/request/CreateFormApplicationRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/FormApplicationCountResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/command/CreateFormApplicationCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/FormApplicationCountQuery.java
Labels: D-0

#256 [DDING-108] 동아리 지원 결과 email 전송 API 구현
  build.gradle
  src/main/java/ddingdong/ddingdongBE/common/config/AmazonS3Config.java
  src/main/java/ddingdong/ddingdongBE/common/config/AsyncConfig.java
  src/main/java/ddingdong/ddingdongBE/domain/club/service/dto/command/UpdateClubInfoCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/form/api/CentralFormApi.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/CentralFormController.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/request/SendApplicationResultEmailRequest.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormService.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/command/SendApplicationResultEmailCommand.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/repository/FormApplicationRepository.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/GeneralFormApplicationService.java
  src/main/java/ddingdong/ddingdongBE/email/SesEmailService.java
  src/main/java/ddingdong/ddingdongBE/email/dto/EmailContent.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImplTest.java
Labels: ✨기능, D-0

#269 [DDING-000] 지원하기 시 응답기간 검증 로직 추가
  src/main/java/ddingdong/ddingdongBE/common/exception/FormException.java
  src/main/java/ddingdong/ddingdongBE/common/exception/InvalidatedMappingException.java
  src/main/java/ddingdong/ddingdongBE/domain/form/controller/dto/response/UserFormResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeCentralFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/FacadeUserFormServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/form/service/dto/query/UserFormQuery.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeUserFormApplicationServiceImpl.java
  src/test/java/ddingdong/ddingdongBE/domain/club/service/FacadeCentralClubServiceImplTest.java
Labels: 🎯리팩토링, D-2

#270 [DDING-000] 파일 폼지 응답 presignedUrl 발급 API 구현
  src/main/java/ddingdong/ddingdongBE/file/api/S3FileAPi.java
  src/main/java/ddingdong/ddingdongBE/file/controller/S3FileController.java
Labels: 🎯리팩토링, D-0

#271 [DDING-000] 파일 타입 폼 응답 presignedUrl 발급 API 인증 허용 추가
  src/main/java/ddingdong/ddingdongBE/common/config/SecurityConfig.java
Labels: 🎯리팩토링, D-0

#274 [DDING-000] 지원서 상세조회시 파일정보 명세 추가
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataService.java
  src/main/java/ddingdong/ddingdongBE/domain/filemetadata/service/FileMetaDataServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/controller/dto/response/FormApplicationResponse.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/FacadeCentralFormApplicationServiceImpl.java
  src/main/java/ddingdong/ddingdongBE/domain/formapplication/service/dto/query/FormApplicationQuery.java
Labels: D-2

#276 [DDING-000] 동아리 모집 기간 체크 로직 수정
  src/main/java/ddingdong/ddingdongBE/domain/club/service/FacadeUserClubServiceImpl.java
Labels: 🎯리팩토링, D-0
